version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: gendev-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: gendev_db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
  server:
    image: "ghcr.io/nomiez/gendev-chat-ui/server:preview"
    container_name: gendev-server
    ports:
      - "8080:80"
    depends_on:
        - postgres
    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: postgres
      DATABASE_USERNAME: gendev_db
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: ${TOKEN_EXPIRE_MINUTES}
    networks:
        - backend
  client:
    image: "ghcr.io/nomiez/gendev-chat-ui/client:preview"
    container_name: gendev-client
    ports:
      - "3000:80"
    networks:
      - frontend

networks:
  frontend:
    name: gendev-network-frontend
  backend:
    name: gendev-network-server

volumes:
  postgres-data: