version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: gendev-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: gendev_db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gendev-network
  server:
    image: "ghcr.io/nomiez/gendev-chat-ui/server:preview"
    container_name: gendev-server
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: postgres
      DATABASE_USERNAME: gendev_db
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: ${TOKEN_EXPIRE_MINUTES}
    networks:
      - gendev-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/docs" ]
      interval: 30s
      timeout: 2s
      retries: 5
  client:
    image: "ghcr.io/nomiez/gendev-chat-ui/client:preview"
    depends_on:
      server:
        condition: service_healthy
    container_name: gendev-client
    ports:
      - "3000:80"
    networks:
      - gendev-network

networks:
  gendev-network:
    name: gendev-network

volumes:
  postgres-data: