# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build the client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on:
      ubuntu-latest
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt

      - name: Extract OpenAPI spec
        run: |
          export SKIP_DB_CONNECTION=True
          python server/extract-openapi.py app.main:app
          mv server/openapi.yaml client/openapi_generated.yaml

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          working-directory: ./client
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          working-directory: ./client
          cmd: install --frozen-lockfile # will run `yarn install` command

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          working-directory: ./client
          cmd: build # will run `yarn build:prod` command

      - name: Upload aritfacts
        uses: actions/upload-artifact@v3
        with:
          working-directory: ./client
          name: build
          path: build